exclude: ^venv\/$
repos:
    - repo: local
      hooks:

          - id: isort
            name: isort
            entry: isort
            language: system
            types: [python]
            args: ["--check", "--ignore-whitespace"]

          - id: flake8
            name: flake8
            entry: flake8
            language: system
            types: [python]